trigger:
- master

variables:
  solution: 'src\src.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: BuildOnWindows
  displayName: "Build and test on Windows"
  pool:
    name: 'Hosted Windows 2019 with VS2019'
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Install .net core 3.0 (preview)'
    inputs:
      version: '3.0.100-preview6-012264'
  - task: MSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildVersion: '16.0'
      msbuildArguments: '/m /restore'
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: | 
        src\**\*test*.dll
        !src\**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      runOnlyImpactedTests: false
      runInParallel: true
      codeCoverageEnabled: true