trigger:
- master

variables:
  buildConfiguration: 'Release'
  system.debug: true
  system_accesstoken: $(System.AccessToken)

jobs:
- job: BuildOnWindows
  displayName: "Build and test on Windows"
  pool:
    name: 'Hosted Windows 2019 with VS2019'
  steps:
  - task: PowerShell@2
    inputs:
      filePath: "scripts/Build.ps1"
      arguments: "-BuildRepos"
  - task: PowerShell@2
    inputs:
      filePath: "scripts/Test.ps1"
      arguments: "-includeMSBuildTests"